version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        networks:
            - nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./ssl_certs:/etc/nginx/certs
            - ./config/nginx_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
            - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
    nginx:
        external:
            name: nginx-proxy
